// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbjqristxtvhmdpyddxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFianFyaXN0eHR2aG1kcHlkZHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NzIwNTgsImV4cCI6MjA1MzI0ODA1OH0.ceM-0BTkCItHYdOy74rEOgaEjGWCsdCDuxL9NGjGT-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);